name: CI Check

on: [ push ]

concurrency:
  group: ${{ github.ref }}-check
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Checkout Edge Plugins
        run: |
          git clone https://github.com/hivemq/hivemq-edge.git ../hivemq-edge
          cd ../hivemq-edge
          git checkout ${GITHUB_REF#refs/heads/} || true
      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Check
        run: ./gradlew check
